name: Ejecución Manual de LS

on:
  push:
    branches:
      - main

jobs:
  run-ls:
    runs-on: self-hosted
    steps:
    - name: Imprimir PATH
      run: echo $PATH
    - name: Ejecutar comando LS v2
      run: |
        cd ~/Escritorio/deploy
        ls -l
    - name: Imprimir mensaje del último commit
      run: git log -1 --pretty=%B
    - name: Imprimir la rama actual y el último mensaje de commit
      run: |
        echo "Rama actual: $(git branch --show-current)"
        echo "Último mensaje de commit: $(git log -1 --pretty=%B)"
    - name: Extraer versión del mensaje de commit
      run: |
        VERSION_TAG=$(git log -1 --pretty=%B | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+') || echo "No se encontró la versión en el commit"
        if [ "$VERSION_TAG" == "No se encontró la versión en el commit" ]; then
          echo "$VERSION_TAG"
          exit 1
        fi
        FILE_PATH=~/Escritorio/deploy/docker-compose.yml
        sed -i "s|image: gcr.io/road-321321/sigmamx:v.*|image: gcr.io/road-321321/sigmamx:$VERSION_TAG|g" "$FILE_PATH"
