name: Ejecución Manual de LS

on:
  workflow_dispatch:

jobs:
  run-ls:
    runs-on: self-hosted
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Ejecutar comando LS
      run: ls -l